chore: update readme into multi steps setup

diff --git a/run_onchange_before_install-packages.sh.tmpl b/run_onchange_before_install-packages.sh.tmpl
--- a/run_onchange_before_install-packages.sh.tmpl
+++ b/run_onchange_before_install-packages.sh.tmpl
@@ -1,7 +1,18 @@
 {{ if eq .chezmoi.os "darwin" -}}
 #!/bin/bash
+set -euo pipefail
 
-brew bundle --verbose --file=/dev/stdin <<EOF
+if [ -x /opt/homebrew/bin/brew ]; then
+    brew_bin=/opt/homebrew/bin/brew
+elif [ -x /usr/local/bin/brew ]; then
+    brew_bin=/usr/local/bin/brew
+else
+    echo "ERROR: Homebrew is not installed." >&2
+    exit 1
+fi
+
+
+"$brew_bin" bundle --verbose --file=/dev/stdin <<EOF
 {{ range .packages.darwin.taps -}}
 tap {{ . | quote }}
 {{ end -}}
